name: Bug Report
description: Report a bug in the Mainframe SDK
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of @maikers/mainframe-sdk are you using?
      placeholder: e.g., 1.0.1
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: Solana Network
      description: Which Solana network are you using?
      options:
        - mainnet-beta
        - devnet
        - testnet
        - localnet
    validations:
      required: true

  - type: dropdown
    id: wallet
    attributes:
      label: Wallet Provider
      description: Which wallet are you using?
      options:
        - Phantom
        - Solflare
        - Backpack
        - Glow
        - Other
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Initialize SDK with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { createMainnetSDK } from '@maikers/mainframe-sdk';
        
        const sdk = createMainnetSDK();
        // Your code that reproduces the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually occurred, include error messages
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - Node.js version:
        - Browser (if applicable):
        - Operating System:
        - TypeScript version:
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: Any additional information that might help solve the issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal code example that reproduces the issue
          required: true
        - label: I am using a supported SDK version (check releases)
          required: true
