name: Feature Request
description: Suggest a new feature for the Mainframe SDK
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see
      placeholder: Brief description of the proposed feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the use case or problem this feature would address
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Detailed description of your proposed solution
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas for how the API should look, share them here
      render: typescript
      placeholder: |
        // Example API design
        const result = await sdk.newFeature({
          option1: 'value',
          option2: true
        });
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my project
        - Critical - Essential for adoption
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Core SDK functionality
        - Security & Encryption
        - Storage & IPFS/Arweave
        - Wallet Integration
        - Agent Management
        - Performance & Monitoring
        - Developer Experience
        - Documentation
        - Testing & Debugging
        - Framework Integration (Anchor, React, etc.)
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered or are currently using
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        1. When building a trading bot, I need to...
        2. For NFT collection management, it would help to...
        3. In production environments, this would enable...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references
      placeholder: Links to similar features in other SDKs, mockups, related discussions, etc.
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature myself
          required: false
        - label: I would be willing to help test this feature
          required: false
        - label: I would be willing to provide feedback during development
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
        - label: This feature aligns with the SDK's security-first and production-ready goals
          required: true
        - label: I have provided clear use cases and problem description
          required: true
